# GitHub Sponsors configuration
# Uncomment and add your username if you set up GitHub Sponsors
# github: N1KH1LT0X1N

# Other sponsorship platforms (uncomment and add your username)
patreon: Nikhil_Pise
ko_fi: nikhil_pise
# buy_me_a_coffee: your-buymeacoffee
# custom: ["https://your-website.com/donate"]

# Note: Remove this file if you don't want to accept sponsorships