name: Repository Metrics

on:
  schedule:
    - cron: "0 2 * * 0"  # Runs weekly on Sunday at 2 AM
  workflow_dispatch:

permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate metrics report
        run: |
          echo "=== Repository Metrics ===" > metrics-report.txt
          echo "Generated on: $(date)" >> metrics-report.txt
          echo "" >> metrics-report.txt
          echo "Files: $(find . -type f | wc -l)" >> metrics-report.txt
          echo "Lines of code: $(find . -name '*.md' -o -name '*.yml' -o -name '*.yaml' | xargs wc -l | tail -n 1)" >> metrics-report.txt
          cat metrics-report.txt
      
      - name: Upload metrics artifact
        uses: actions/upload-artifact@v3
        with:
          name: metrics-report
          path: metrics-report.txt
          retention-days: 30
