name: Update Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-update
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Update README with latest stats
        run: |
          echo "Profile stats updated on $(date)" >> .github/last-update.txt
          echo "::notice::Profile stats workflow completed successfully"
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/last-update.txt || true
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update profile stats [skip ci]"
          git push || true
        continue-on-error: true
